// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbgs5gIQAgIvLapdlYo3kDu66qbDRlriw',
    appId: '1:423580756418:web:43751c558e0a7fec9f0e5b',
    messagingSenderId: '423580756418',
    projectId: 'bulk-basket',
    authDomain: 'bulk-basket.firebaseapp.com',
    storageBucket: 'bulk-basket.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-j1yVNNwHvd9l2vmCNbKqhEovDHQOiIE',
    appId: '1:423580756418:android:37bf54ecb566b1099f0e5b',
    messagingSenderId: '423580756418',
    projectId: 'bulk-basket',
    storageBucket: 'bulk-basket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCuAum3j7RxZQmlLwSO2r4-LnJocxDX-0',
    appId: '1:423580756418:ios:0e400b98869b88b39f0e5b',
    messagingSenderId: '423580756418',
    projectId: 'bulk-basket',
    storageBucket: 'bulk-basket.firebasestorage.app',
    iosBundleId: 'com.example.bulkBasket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCuAum3j7RxZQmlLwSO2r4-LnJocxDX-0',
    appId: '1:423580756418:ios:0e400b98869b88b39f0e5b',
    messagingSenderId: '423580756418',
    projectId: 'bulk-basket',
    storageBucket: 'bulk-basket.firebasestorage.app',
    iosBundleId: 'com.example.bulkBasket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbgs5gIQAgIvLapdlYo3kDu66qbDRlriw',
    appId: '1:423580756418:web:9f816a8166b5a2aa9f0e5b',
    messagingSenderId: '423580756418',
    projectId: 'bulk-basket',
    authDomain: 'bulk-basket.firebaseapp.com',
    storageBucket: 'bulk-basket.firebasestorage.app',
  );
}
